### ISSUE TITLE
support metrics per application

### ISSUE THREAD

**Issue by kwmonroe** [CanonicalLtd/layer-metrics#2]
Some metrics are best reported per-application, and not per unit.  For example, members of a zookeeper cluster.  My metric simply does a word count of a conf file:

```yaml
metrics:
  servers:
    type: gauge
    description: number of zookeeper servers in the cluster
    command: grep ^server /etc/zookeeper/conf/zoo.cfg  | wc -l
```

When displaying this metric, I only want one count across the whole application, regardless of how many units are deployed.  Instead, I get this:

```bash
$ juju metrics zookeeper
UNIT       	           TIMESTAMP	 METRIC	VALUE
zookeeper/0	2017-03-19T17:09:43Z	servers	    3
zookeeper/1	2017-03-19T17:04:45Z	servers	    3
zookeeper/2	2017-03-19T17:07:11Z	servers	    3
```

One approach to address this would be to classify the metric in `metrics.yaml` as something like "leader-only", so it would only run `collect-metrics` on the leader of an application.  That yaml might looks something like this:

```yaml
metrics:
  servers:
    type: gauge
    leader-only: true
    description: number of zookeeper servers in the cluster
    command: grep ^server /etc/zookeeper/conf/zoo.cfg  | wc -l
```

Or perhaps introduce a new metric type like "gauge-leader" that does the same thing -- only run metric collections on the leader of the application:

```yaml
metrics:
  servers:
    type: gauge-leader
    description: number of zookeeper servers in the cluster
    command: grep ^server /etc/zookeeper/conf/zoo.cfg  | wc -l
```
